@startuml
start
repeat :Input Data\n Transaksi;
:Klik Tombol "Bayar";
backward :Tampilkan alert"Belum ada\n item yang ditambahkan.";
repeat while (Item di keranjang ada?) is (tidak) not (ya)
if (Metode Pembayaran?) then (Cash)
    :Kirim data ke API storeTransaction;
    if (Response Berhasil?) then (Ya)
        :Tampilkan alert "Transaksi\nberhasil disimpan!";
        :Redirect ke Halaman\n Index Transaksi;
    else (Tidak)
        :Tampilkan alert "Terjadi kesalahan \nsaat menyimpan transaksi";
    endif

else (Midtrans)
    :Request Snap\nToken ke API;
    if (Token Diterima?) then (Ya)
        :Buka Snap QRIS;
        :User Lakukan\nPembayaran;
        if (Pembayaran Berhasil?) then (Ya)
            :Tampilkan alert\n"Pembayaran berhasil!";
            :Redirect ke Halaman\nIndex Transaksi;
        else (Tidak)
            :Tutup Snap / Gagal bayar;
        endif
    else (Token Gagal)
        :Tampilkan alert "Invalid\ntoken / Midtrans error";
    endif

endif
stop
@enduml