@startuml
start
repeat :1;
:2;
backward :4;
repeat while (3) is (tidak) not (ya)
if (5) then (Cash)
    :6;
    if (7) then (Ya)
        :8;
        :9;
    else (Tidak)
        :10;
    endif
else (Midtrans)
    :11;
    if (12) then (Ya)
        :13;
        :14;
        if (15) then (Ya)
            :16;
            :17;
        else (Tidak)
            :18;
        endif
    else (Token Gagal)
        :19;
    endif
endif
stop
@enduml